name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da Imagem Docker   
      uses: docker/build-push-action@v6
      with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: | 
            opmartins/aula-primeira-pipeline:v${{ github.run_number }} 
            opmartins/aula-primeira-pipeline:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5
    - name: Configuração do contexto do Kubernetes
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_KUBECONFIG }} #Ficou faltando o kubeconfig, por que não tenho cluster no ar.
    - name: Instalar AWS CLI e aws-iam-authenticator
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        curl -o aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/latest/download/aws-iam-authenticator-linux-amd64
        chmod +x aws-iam-authenticator
        sudo mv aws-iam-authenticator /usr/local/bin
    - name: Execução do manifest
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          fabricioveronez/aula-primeira-pipeline:v${{ github.run_number }}
